# NumPy

### NumPy stands for numeric python and it is the library for numeric and scientific computing. 

### It consists of multidimentional array objects and a collection of routines for processing those arrays.

## Creating NumPy array

### 1.Single dimebtional array

In [1]:
import numpy as np
l1 = [1,2,3,4]
n1 = np.array(l1)
n1

array([1, 2, 3, 4])

In [2]:
#in a single command
n1_1 = np.array([1,2,3,4])
n1_1

array([1, 2, 3, 4])

In [3]:
type(n1)

numpy.ndarray

In [4]:
type(n1_1)

numpy.ndarray

### 2.Multidimentional array

In [5]:
import numpy as np
n2 = np.array([[10,20,30,40],[40,50,60,70]])
n2

array([[10, 20, 30, 40],
       [40, 50, 60, 70]])

In [6]:
type(n2)

numpy.ndarray


### Initializing NumPy Array - with 'zeros'

### import numpy as np #This command is not requeried for each new arry creation. Once created within a session, it works for all new array. 

In [7]:
import numpy as np
n1 = np.zeros((1,2)) #1,2 - 1 row, 2 column
n1

array([[0., 0.]])

In [8]:
n2 = np.zeros((5,5))
n2

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

### Initializing NumPy Array - with 'full'

In [9]:
import numpy as np
n1 = np.full((2,2),10) #((2,2),10)- 2 row, 2 column of number 10
n1

array([[10, 10],
       [10, 10]])

In [10]:
n2 = np.full((4,4),6)
n2

array([[6, 6, 6, 6],
       [6, 6, 6, 6],
       [6, 6, 6, 6],
       [6, 6, 6, 6]])

### Initializing NumPy Array - with 'arange' 

n1 = np.arange(10,20) #(10,20)- means from 10 to 20 where 20 is last index and is exculsive.
n1

In [11]:
n2 = np.arange(10,50,5) #(10,50,5)- means from 10 to 50 with interval of 5.
n2

array([10, 15, 20, 25, 30, 35, 40, 45])

### Initializing NumPy Array - with 'random'

In [12]:
n1 = np.random.randint(1,100,5)
#randint is a method for random integer
#(1,100,5) means between 1 to 100 any 5 random number
n1
#n1 will cange every time the code is run.

array([74, 96, 78, 67, 47])

### NumPy Shape - check shape of array with 'shape'

In [13]:
n1

array([74, 96, 78, 67, 47])

In [14]:
n1.shape

(5,)

In [15]:
#Above resuls means 5 row and no column

In [16]:
n1 = np.array([[1,2,3,4],[2,3,4,5]])
n1

array([[1, 2, 3, 4],
       [2, 3, 4, 5]])

In [17]:
n1.shape

(2, 4)

In [18]:
#above result means 2 row 4 column

In [19]:
# can change the shape - mean rows = column and column = rown
n1.shape = (4,2)
n1

array([[1, 2],
       [3, 4],
       [2, 3],
       [4, 5]])

In [20]:
n1.shape

(4, 2)


### Stacking (joining) NumPy Arrays

#### vstack() - for vertical stacking

In [21]:
n1 = np.array([1,2,3,4])
n2 = np.array([9,8,7,6])
np.vstack((n1,n2))

array([[1, 2, 3, 4],
       [9, 8, 7, 6]])

In [22]:
np.vstack((n2,n1))

array([[9, 8, 7, 6],
       [1, 2, 3, 4]])

#### hstack() - for horizontal stacking

In [23]:
n1 = np.array([10,20,30,40])
n2 = np.array([1,2,3,4])
np.hstack((n1,n2))

array([10, 20, 30, 40,  1,  2,  3,  4])

In [24]:
np.hstack((n2,n1))

array([ 1,  2,  3,  4, 10, 20, 30, 40])

#### colunm_stack() as the name suggests😀

In [25]:
np.column_stack((n1,n2))

array([[10,  1],
       [20,  2],
       [30,  3],
       [40,  4]])

In [26]:
np.column_stack((n2,n1))

array([[ 1, 10],
       [ 2, 20],
       [ 3, 30],
       [ 4, 40]])

### Intersection and Difference 

In [27]:
n1 = np.array([10,20,30,40,50])
n2 = np.array([90,80,10,70,50])
np.intersect1d(n1,n2) #intersect1d is the method

array([10, 50])

In [28]:
np.setdiff1d(n1,n2) #setdfif1d is the method - elements from n1 which are not present in n2

array([20, 30, 40])

In [29]:
np.setdiff1d(n2,n1) #elements from n2 which are not present in n1

array([70, 80, 90])

### Addition of arrays

In [30]:
n1 = np.array([10,20])
n2 = np.array([30,40])
np.sum([n1,n2])

100

In [31]:
#Add columns
np.sum([n1,n2],axis=0)

array([40, 60])

In [32]:
#Add Rows
np.sum([n1,n2],axis=1)

array([30, 70])

### Basic Mathematics

In [33]:
#addition
n1 = np.array([10,20,30])
n1 = n1 + 1
n1

array([11, 21, 31])

In [34]:
#Substraction
n1 = n1 - 1
n1

array([10, 20, 30])

In [35]:
#Multiplication
n1 = n1*4
n1

array([ 40,  80, 120])

In [36]:
#Division
n1 = n1/2
n1

array([20., 40., 60.])

### Basic Statistics

In [37]:
#Mean
n1 = np.array([10,20,30,40,50,60])
np.mean(n1)

35.0

In [38]:
#Median
import numpy as np
n1 = np.array([10,20,30,40,50])
np.median(n1)

30.0

In [39]:
#Standard Deviation
np.std(n1)

14.142135623730951

### Save and Load

In [40]:
n1 = np.array([10,20,30,40,50])

In [49]:
np.save('myarray',n1)

In [50]:
new_n1 = np.load('myarray.npy')
new_n1

array([10, 20, 30, 40, 50])